# -*- coding: utf-8 -*-
"""replace_slicetimings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzIkx-jl35R9nRKZ9wvi3IH0L0ga6u5_

## First, import packages
"""

import json
import os
import sys

"""## Read in json from BIDS"""

# Take input from specified path
# json_from_bids = '/content/drive/MyDrive/nenah-bids-slicetiming/data/sub-NENAHC001_dir-AP_run-1_dwi.json'

# Take input from argument
json_from_bids = str(sys.argv[1])

with open(json_from_bids) as jsonFile:
    jsonObject = json.load(jsonFile)
    jsonFile.close()

out = jsonObject['SliceTiming']

print(out)

"""## Read in json from Syngo DICOM, get SliceTiming"""

# Take input from specified path
# json_from_syngo = '/content/drive/MyDrive/nenah-bids-slicetiming/data/NENAHC001_Series-25-SliceTiming-syngo.json'
# Take input from argument
json_from_syngo = str(sys.argv[2])

with open(json_from_syngo) as jsonFile:
    jsonObject_syngo = json.load(jsonFile)
    jsonFile.close()

out_syngo = jsonObject_syngo['SliceTiming']

print(out_syngo)

"""## Replace SliceTiming in BIDS with Syngo"""

jsonObject['SliceTiming'] = out_syngo

print(jsonObject)

"""## Finally, save as new json file"""

# Specify output to a specified path
# json_to_write = '/content/drive/MyDrive/nenah-bids-slicetiming/data/sub-NENAHC001_dir-AP_run-1_dwi_SliceTimings_updated.json'

# https://stackoverflow.com/questions/17055117/python-json-dump-append-to-txt-with-each-variable-on-new-line
# with open(json_to_write, 'w') as jsonFile:
filename = str(sys.argv[1]).split('.')[0]
with open(os.path.join(filename, '_SliceTimings_updated.json'), 'w') as jsonFile:
    json.dump(jsonObject, jsonFile, indent=2)
    jsonFile.close()

# The json file can be accessed at uos-15263: /local/scratch/disk2/research/NENAH_BIDS/rawdata/sub-NENAHC001/dwi